### ISSUE TITLE
Prismarine coral plane makes other invisible (redering error)

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/Upgrade-Aquatic#100]
![image](https://user-images.githubusercontent.com/38932715/79058996-8ed44200-7c29-11ea-91a6-bb72a1763ebd.png)

**Comment by SmellyModder** [comment]
Forge Bug, report it to them, can be reproduced in many other ways, such as Bubble Columns' bubbles not being visible out of water
