### ISSUE TITLE
Doesnt seem like prismarine coral can be used to power conduits anymore

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/Upgrade-Aquatic#108]
![image](https://user-images.githubusercontent.com/38932715/79685506-32a38c00-81ee-11ea-9b8c-6591b5656c71.png)

**Comment by SmellyModder** [comment]
Hmm yes, this appears to be happening. Forge changed the way conduits determine which blocks can activate them not too long ago, the vanilla blocks we add as activation to it won't work anymore after a fix for this unfortunately due to the changes made by Forge.

**Comment by SmellyModder** [comment]
Fixed by 6b06bf6
