### ISSUE TITLE
Add compatibility for Corail's Woodcutter

### ISSUE THREAD

**Issue by Insane96** [minecraftabnormals/Upgrade-Aquatic#109]
So we can use planks into the woodcutter

**Comment by SmellyModder** [comment]
It appears we cannot, as it is hardcoded in that mod: https://github.com/Corail31/woodcutter/blob/master/src/main/java/ovh/corail/woodcutter/compatibility/SupportMods.java

If you still wish to have this contact the Corail's Woodcutter Mod.
