### ISSUE TITLE
Guardian spines are subtitled as pistons when extending/retracting

### ISSUE THREAD

**Issue by muzikbike** [minecraftabnormals/Upgrade-Aquatic#110]
Doesn't really make sense given they're not pistons.

Possibly happens due to a sound event being reused, so a unique one should probably be added with unique subtitles.

![2020-04-23_09 21 15](https://user-images.githubusercontent.com/52297970/80076436-1bdd9c00-8544-11ea-995f-caa2527a1d7e.png)

**Comment by bageldotjpg** [comment]
Same as the others - kinda nitpicky, we will get to it if we get to it
