### ISSUE TITLE
Stripped driftwood logs and wood have inconsistent IDs from vanilla logs and wood

### ISSUE THREAD

**Issue by muzikbike** [minecraftabnormals/Upgrade-Aquatic#112]
The "stripped" should come before the rest of the ID, not after.
![2020-04-23_09 17 50](https://user-images.githubusercontent.com/52297970/80078034-3ca6f100-8546-11ea-9bc4-fe0fce7a4886.png)
![2020-04-23_09 17 51](https://user-images.githubusercontent.com/52297970/80078039-3dd81e00-8546-11ea-8c77-55d66e8fa797.png)
![2020-04-23_09 18 06](https://user-images.githubusercontent.com/52297970/80078042-3f094b00-8546-11ea-9075-bb833112c995.png)
![2020-04-23_09 18 07](https://user-images.githubusercontent.com/52297970/80078049-403a7800-8546-11ea-881f-8fb4f12d67bb.png)

**Comment by bageldotjpg** [comment]
changing the id would result in deleting the blocks from multiple worlds, and the id isn't super important. this may be changed in the future but currently not planned so that the blocks aren't deleted from worlds

**Comment by muzikbike** [comment]
Could a data fixer be added, or are those only for vanilla?
