### ISSUE TITLE
No subtitle for placing a tooth lantern

### ISSUE THREAD

**Issue by muzikbike** [minecraftabnormals/Upgrade-Aquatic#113]
Would have expected a "Block placed" subtitle like with other blocks, but this does not happen.

The tooth lantern may be reusing the eye of ender addition sound event, which is resulting in no subtitle showing up (in 1.15, and will result in an incorrect one in 1.16), so a unique sound event should probably be added for tooth lanterns, which refers to the same sound files but links to the generic block placement subtitle instead.

![2020-04-23_09 40 35](https://user-images.githubusercontent.com/52297970/80078449-dc647f00-8546-11ea-9031-05525e513458.png)

**Comment by bageldotjpg** [comment]
Seems awfully nitpicky, if we get to it we get to it.
