### ISSUE TITLE
Elder eye uses entity renderer

### ISSUE THREAD

**Issue by muzikbike** [minecraftabnormals/Upgrade-Aquatic#114]
Not sure if this is neccessary, since it does limit customization via models.

![2020-04-23_10 30 59](https://user-images.githubusercontent.com/52297970/80083663-c6a68800-854d-11ea-8520-692eb6853be3.png)

**Comment by bageldotjpg** [comment]
Elder Eyes use entity renderers because there are future plans that will require it like this
