### ISSUE TITLE
Nautilus uses generic hurt/death sounds and subtitles

### ISSUE THREAD

**Issue by muzikbike** [minecraftabnormals/Upgrade-Aquatic#115]
Unique sounds and subtitles should probably be added.

![2020-04-23_10 35 34](https://user-images.githubusercontent.com/52297970/80084181-6d8b2400-854e-11ea-9d52-b74c50d2c8b9.png)
![2020-04-23_10 35 46](https://user-images.githubusercontent.com/52297970/80084189-6fed7e00-854e-11ea-84cb-8c2cf9b3631b.png)

**Comment by bageldotjpg** [comment]
Sound designers aren't easy to get and tend to be fairly busy, if we are able to get sounds for them we will consider it
