### ISSUE TITLE
Certain mobs reuse vanilla sound events resulting in unintuitive subtitles

### ISSUE THREAD

**Issue by muzikbike** [minecraftabnormals/Upgrade-Aquatic#116]
Unique sound events should probably be added so that subtitles that aren't so confusing can be added.

Pike reuses the salmon sound event, lionfish the pufferfish sound event and flares phantoms

![2020-04-23_10 37 44](https://user-images.githubusercontent.com/52297970/80084483-d6729c00-854e-11ea-9aca-3a16d01ccd0b.png)
![2020-04-23_10 38 00](https://user-images.githubusercontent.com/52297970/80084491-d96d8c80-854e-11ea-8d01-7c356540af4a.png)
![2020-04-23_10 38 13](https://user-images.githubusercontent.com/52297970/80084497-da9eb980-854e-11ea-8886-6cd90fe199d6.png)

**Comment by SmellyModder** [comment]
These are placeholder sounds for them, again, they're planned to be replaced with custom ones eventually.
