### ISSUE TITLE
Parsing error loading recipe a dozen times

### ISSUE THREAD

**Issue by JanThomas118** [minecraftabnormals/Upgrade-Aquatic#121]
When loading a world this mod seems to have dozens of recipe loading errors.
It seems like all recipes using some kind of kelp stone bricks want a "stone_bricks" even though those stone bricks are registered as "stone_brick". So either change the registry name, or change all recipes.
I have a full log here: https://paste.ee/p/i5hhp
I cleaned up the log a lot to only contain those recipe errors here: https://hastebin.com/arupegozoj.makefile (makefile? wtf?)
I am on the latest version of the mod for 1.14.4

**Comment by SmellyModder** [comment]
Sorry, but 1.14.4 will no longer be receiving any bug fixes, and these log errors have been fixed in the 1.15.2 versions of the mod.

Also, these log errors shouldn't impact your gameplay, since a lot of the kelp blocks are unobtainable anyways.
