### ISSUE TITLE
Game crahes because pickerleweed tries to set "fake_watterlogged" on leaves

### ISSUE THREAD

**Issue by JanThomas118** [minecraftabnormals/Upgrade-Aquatic#122]
I have this mod and traverse installed and the game crashed on seed "-6582274873432248708", 
The game crashes every time i load the world now, upon creating a second world, this did not happen again.
It seems that when https://github.com/minecraftabnormals/Upgrade-Aquatic/blob/13e7bbe0659ffe25ed0035db400a9916275d3d3c/src/main/java/com/teamabnormals/upgrade_aquatic/common/blocks/BlockPickerelweedDouble.java#L87-L90 is executed, the blockstate for the block above is set to fake_watterlogged, but it never checks if the above block is even a pickerleweed upper block. If i understand your code correctly
Crash log: https://paste.ee/p/0aOsT
I am using the latest version for 1.14.4

**Comment by SmellyModder** [comment]
1.14.4 will not be receiving any more bugfixes as I said in the other commit. 

I'll see if this bug is still occurring in the 1.15.2 versions of the mod and if it is I will fix it.
