### ISSUE TITLE
Corrupt World

### ISSUE THREAD

**Issue by gamatism** [minecraftabnormals/Upgrade-Aquatic#13]
Out of nowhere apon logging in the mod had become corrupt somehow, and all the items from the mod in my world disappeared ruining the entire world i had built that had revolved around it. No error message. game initially crashed but now it let me log in except with a messed up world

**Comment by SmellyModder** [comment]
Likely to due with the mod being loaded incorrectly somehow on the previous save and when updating caused this so I'm gonna close this issue
