### ISSUE TITLE
[Suggestion] Kelp Blocks

### ISSUE THREAD

**Issue by Kingdomall** [minecraftabnormals/Upgrade-Aquatic#131]
As I'm aware that kelp blocks exist, it'd be nice if, like hay bales, you take substantially less damage when you fall on them. I like that this mod adds some new uses for kelp since it's so abundant.

**Comment by fivelol** [comment]
I don't think this is necessary because that's already the niche of hay bales, given the abundance of kelp you mention there's no need for it to take another of wheat's few niches.
