### ISSUE TITLE
Blue Pickerelweed rendering broken in flower pots

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/Upgrade-Aquatic#136]
![image](https://user-images.githubusercontent.com/38932715/82115464-c007cc80-9717-11ea-9960-990f76325363.png)

**Comment by SmellyModder** [comment]
Fixed by [1.6.1](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic/files/2958503)
