### ISSUE TITLE
Quark Compatibility - Dyes from Corals

### ISSUE THREAD

**Issue by SpiderKolo** [minecraftabnormals/Upgrade-Aquatic#137]
Vanilla Corals gain recipes for Dies from Quark.
It could be great if there were recipes for the other coral added by this mod, as well as dead Coral which didn't get recipe for the Gray Dye.

**Comment by SmellyModder** [comment]
Possibly, preferably this should be done on Quark's side, but I'll consider it.

**Comment by SmellyModder** [comment]
Added in commit 2c23b19
