### ISSUE TITLE
[Suggestion] Optional Config where you get 4 Coral Blocks form 4 Corals instead of 1

### ISSUE THREAD

**Issue by SpiderKolo** [minecraftabnormals/Upgrade-Aquatic#138]
Self Explanatory Title is Self Explanatory.

Why would we even want this setting?
I think it could be nice to have an option to make process of getting coral blocks a bit less tedious.

I can see few people wanting this feature.

**Comment by SmellyModder** [comment]
This really doesn't seem balanced, sorry.
