### ISSUE TITLE
[Suggestion] Prismarine Bow and Arrows maybe?

### ISSUE THREAD

**Issue by SpiderKolo** [minecraftabnormals/Upgrade-Aquatic#139]
We have Trashers Teeth and we can make Rods from Prismarine to craft Tridents... and also Packed Prismarine Rods...
Tooth have many other cool uses, but how about a bit more?
I had an idea for an Arrow which could fit amazingly with both of those elements.

Prismarine Arrows
Pros:
+ Can go through water similarly to Tridents
+ Normal Damage on land and Extra Damage when hitting creatures underwater (not just creatures from underwater)
+ Penetrate small mobs
+ Could be infused with potions

Cons:
- More expensive crafting recipy - would require Thrasher Tooth, Prismarine Rod and Feather to craft eight Prismarine Arrows.
- Can be shot only from Crossbow or Prismarine Bow.

Originally I wanted to stop on just Arrow, because at the time I was just thinking what cool stuff could be made with the Tooth... but then I realized that we might need something to shoot it from.
If you read cons of the Arrow, you already know I'm thinking about new Bow:

Prismarine Bow
Pros:
+ Can shoot any type of Arrow (Normal and Prismarine ones, as well as Tipped Arrows)
+ Arrows fly faster and further, Normal arrows fly a bit further underwater before they lose speed
+ Can be enchanted with some more enchants from other weapons (will explain bellow)
+ Deals way more damage compared to normal bow
Cons:
- Way Harder to fully charge (you can give it enchantment to kinda negate that weakness)
- While have access to some unique enchantments, it also looses some more universal options as it's cost

Prismarine Bow is supposed to be the "Sniper" kind of weapon - very long charge rate, but also very powerful when it hits. It's especially effective with new arrows, but it's also desant with normal arrows.
So... to show this, let me explain few enchantments...

Enchanting:
I was looking at enchantments which would fit Aquatic feel very well, as well as for the overall use of this bow: Powerful Hits from Far Away.
To justify some of the choices, I will first point few Enchantments I don't think fit very well with the Aquatic Bow and then show replacements. There will be like two enchantments which will go for either balance reason or because lorewise it wouldn't fit:
**Have to go:**
**Infinity:** I don't think infinite amount of Prismarine Arrows could be balanced really. There isn't anything not exacly fitting in terms of lore, but it is more for the balance sake.
**Replacement:**
**Loyalty I-III** - This enchantment normally makes Trident comeback to you after it hits something. Here highier level means shorter time of coming back.
For the Bow that won't work because you don't throw Bow... but you shoot arrows... which could comeback...
You could make it so Arrows have chance to comeback to the player who shot with that bow - 25% or maybe even 30% per level (I'm more for the 25% to be honest).
I think this one would fit, because we want to use this bow from far away, and this enchantment will let us pick used arrow from very far away.

**Have to go:**
**Flame** - if this bow benefit from shooting things underwater, how exactly useful will be lighting things on fire? Not super useful.
But now what will act as our element of destruction? Fire was cool, but this bow can't have it because it's Aquatic Bow...
There is one very good replacement...
**Replacement:**
**Channeling** - THUNDER! Oh yeah!
This enchantment is an amazing option for weapon focused on dealing damage from far away.
It will only work during Thunderstorms which is notably the worst part about this enchantment, but to be completely fair, it would fit this weapon thematically far more than Fire which would be useless underwater.
Also - Channeling, unlike Flame, deals more damage instantly because of the Lightning which hits target. Flame will just apply Fire on opponent.

Now... there won't be more enchantments which I imagine we could be replacing, but there are some more which could fit as well to the new Bow:

**Piercing I-IV** - while I don't know how efficient this enchantment would be, but this Bow does charge very long after all, so it makes sense it would make little holes through enemies when you finally release it...

**Quick Charge I-III** - I mentioned that this weapon have slower charge rate than normal bow, meaning it will shoot less arrows in the same amount of time than normal Bow.
I think it would be just fair if that weapon had something which would slightly negate the downsite.

**Impaling I-V** - While I don't think it shouldn't be able to NOT have Power, I also don't think we should deny Impaling either - it's perfect for Underwater ventures.

So... how many enchantments we can apply on our Prismarine Bow?
At once? Well... two pairs of enchantments I feel should be Mutually Exclusive to one another:
Impaling VS Power
One offers amazing fighting chance against creatures of the sea, other one offers more flexibility.
Punch VS Piercing
It's illogical to both Pierce something and Push something. You either push really hard, or Push soo hard you go through it.
(Well... it's not that illogical, but for the sake of balance let's say those two should be mutually exclusive).
That leaves us with 5 other enchantment which have no issues with one another:
Channeling, Quick Charge, Loyalty, Unbreaking, Mending.
Those Five + Two out of Four we have to choose from gives us up to Seven Enchantments.

What you think about this idea?

**Comment by fivelol** [comment]
Thank you for putting in the effort for you idea, but in future bigger ideas should go on our discord server. We currently don't see the need for a prismarine bow because its quite akin to the trident in many regards, and the trident already functions as the water themed ranged weapon, and shares many of the enchantments you've suggested here.
