### ISSUE TITLE
Vertical slabs crash with the Lord of the Rings mod

### ISSUE THREAD

**Issue by WenXin20** [minecraftabnormals/Upgrade-Aquatic#140]
`Forge v31.1.74`
`Minecraft v1.15.2`
`Upgrade Aquatic v1.5.1`
[`LOTR v1.1`](https://lotrminecraftmod.fandom.com/wiki/Updates/Renewed) 

This mod isn't on Curseforge and is not open source, so I'm not sure if anything can be done on this end, but when the Lord of the Rings mod is installed with Upgrade Aquatic, it crashes.

Based on the log, the crash seems to be caused by the vertical slabs mechanic, added by LOTR mod.

[Crash Log](https://gist.github.com/WenXin20/1694328f7bc5e37e8a744a1e73472a8e) 
Error starts at `[12:11:03]` in the log.

Issue reported to LOTR here: https://lotrminecraftmod.fandom.com/wiki/Thread:436820?useskin=oasis

**Comment by SmellyModder** [comment]
This seems it's the fault of the LOTR mod.
