### ISSUE TITLE
Plant spreading and animation

### ISSUE THREAD

**Issue by disastercube** [minecraftabnormals/Upgrade-Aquatic#142]
While exploring your world, coming across random circular shaped flower gardens is really unrealistic and not vanilla looking. It ruins the natural looks of the game. Making them of different shapes with a bit more space between each plant would completely change the aspect of the game in a much better way. Adding things like leafs and other flower types could also enhance the looks. Removing plant animation and adding  shader waving plants compatibility would make it look far better. Also, being able for plants such as pickerelweed to spawn on sand would help a lot in this.

**Example before:**

![2020-05-25_13 20 39](https://user-images.githubusercontent.com/62697421/82809268-0681c780-9e8c-11ea-88ba-d9147d5cc445.png)

![2020-05-25_13 07 43](https://user-images.githubusercontent.com/62697421/82809421-595b7f00-9e8c-11ea-893b-852ce8967117.png)

**Example after:**

![2020-05-25_13 29 43](https://user-images.githubusercontent.com/62697421/82809314-22856900-9e8c-11ea-8213-6d535f069d4f.png)

![2020-05-25_13 17 04](https://user-images.githubusercontent.com/62697421/82809465-72643000-9e8c-11ea-9f75-66321e7c8446.png)

**Comment by fivelol** [comment]
Not sure what you mean by circular flower gardens, the patches of flowers are somewhat similar to how vanilla generates flower patches, and are not remotely circular. Driftwood is dead wood, so it can't have leaves. Shaders need to add compatibility on their end for their waving, and you can remove plant animations with a resourcepack.

**Comment by disastercube** [comment]
What if a person doesn't want to have a resource pack. Also by circular plant generation is clearly shown in the second picture. Its clear as day as how they spawn and it just looks like white and pink circles and it looks bad especially since is on sand which doesn't have any other types of greens. It is true that that is how vanilla flowers spawn but you can't use the same system when a flower looks more like a bush. You need to add more space.

**Comment by disastercube** [comment]
And yes, its driftwood, but if it is just left like that it doesn't give a good vibe to the game. It gives 1.7.10 mod vibe when people just added random stuff. At being a drift wood doesn't mean it can't have leafs. Usually when barks drift to the shore it also comes with twigs, branches and leaves.

**Comment by disastercube** [comment]
I'm begging you to fix this. Especially in 1.15.2 since the aquatic update. This things ruin the game more then enhance it. I personally wouldn't use this mode and it is just for the reason of it not looking vanilla or natural.
