### ISSUE TITLE
No Jelly and Jelly Torches?

### ISSUE THREAD

**Issue by Burgersim** [minecraftabnormals/Upgrade-Aquatic#148]
Hi, I wasn't sure if this was intended, but it seems that in the most recent Version (1.6.1.) I see Jellyfish swimming about, and Jelly Torches in the JEI Inventory, but it seems the Torches have no recipes, and the Jellyfish don't drop Jelly. Is this a bug or not implemented (yet)?

**Comment by bageldotjpg** [comment]
To get Jelly, you harvest it from Jellyfish by right clicking them using a Prismarine Rod
