### ISSUE TITLE
2-high underwater plants animation bug

### ISSUE THREAD

**Issue by bloche14** [minecraftabnormals/Upgrade-Aquatic#149]
Some of the underwater plants that are 2 blocks high sometimes generate with the top block out of the water. That top block still has the swaying animation as if it was underwater, even though it's not. Probably these plants should either only generate when the entire plant can be underwater, or the top block should not animate when it is in air.

**Comment by bageldotjpg** [comment]
This is working as intended. If the bottom of the plant is moving why wouldn't the top be?

**Comment by bloche14** [comment]
Ah I didn't really sorry. The animation read to me as if the plants are suspended and "floating" in water.
