### ISSUE TITLE
[Suggestion] Configurability of thins in Upgrade Aquatic

### ISSUE THREAD

**Issue by Quizer9O8** [minecraftabnormals/Upgrade-Aquatic#152]
Currently there is no way to configure certain aspects in Upgrade Aquatic.
There are some block/plants/entities I rather have not spawning in certain biomes or dimension at all.
Being able to configure the mod will give everyone the ability to tailor fit their play-style.

**Comment by SmellyModder** [comment]
This has been considered before, and we may do it for more things eventually.
