### ISSUE TITLE
Driftwood logs and planks are crafted into mixed chests instead of driftwood chests (river planks work but not logs)

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/Upgrade-Aquatic#164]
![image](https://user-images.githubusercontent.com/38932715/88246682-10d3fe00-cc50-11ea-9615-548b7828175e.png)

**Comment by SmellyModder** [comment]
Unfortunately, this is due to how Quark excludes chest recipes for the mixed chest.
It'll have to be fixed on their end somehow. We'll try to figure something out
