### ISSUE TITLE
Game crashes every time 

### ISSUE THREAD

**Issue by HaniR125** [minecraftabnormals/Upgrade-Aquatic#17]
Hi, I was palying with your mod for some time and really loved it. Yesterday when I tried to log it it crashed over and over again, it starts with all the mods bud this one. It can be the only one and it crashes. I downoloaded the latest version, it still crashes. I also tried the older ones, it still would not work. I really loved this mod and created a huge world with it which is now corrupted without it. Please, if you find time, would you be able to help me? I am dummy dum about coding and that stuff but I loved the fishes, corals and everything and I would love it back. Thank you so much. 
[crash-2019-09-06_15.53.41-client.txt](https://github.com/minecraftabnormals/Upgrade-Aquatic/files/3584243/crash-2019-09-06_15.53.41-client.txt)

**Comment by SmellyModder** [comment]
Oof sorry to hear about that, but I'm here to help 😃 . What forge version are you running it on?

**Comment by Syndaryl** [comment]
I can confirm this has been crashing since the latest forge updates (still crashing in the stable release that just came out 1.14.4-forge-28.1.0)

**Comment by SmellyModder** [comment]
Noted already
