### ISSUE TITLE
Black eggs

### ISSUE THREAD

**Issue by lozals96** [minecraftabnormals/Upgrade-Aquatic#177]
Every time we go onto the PlayStation we have to delete and then redownload the game to allow it to create a new world. Previous worlds have blacks and nothing will spawn. Is this to do with the new update?

**Comment by bageldotjpg** [comment]
this is for a java edition mod...

**Comment by lozals96** [comment]
> this is a java edition mod...

So is there anything I can do? My little boy is devastated

**Comment by JacksonPlayz** [comment]
Where did you download it from?

**Comment by lozals96** [comment]
> Where did you download it from?

From the official minecaft store on the PlayStation

**Comment by JacksonPlayz** [comment]
We don't distribute our mods through the marketplace. Could you tell us what the name of it?

**Comment by lozals96** [comment]
Aquatic life fishing. Sorry I might have gotten the wrong site then.

**Comment by bageldotjpg** [comment]
Ah, this is the wrong location. This is the Upgrade Aquatic mod for Java Edition / PC Minecraft.

**Comment by lozals96** [comment]
Okay thank you 😊

**Comment by JacksonPlayz** [comment]
We don't create marketplace addons, so no that's not ours. Recommend to contact the team who created it.
