### ISSUE TITLE
1.15.2 Missing Texture

### ISSUE THREAD

**Issue by Yourname942** [minecraftabnormals/Upgrade-Aquatic#184]
There seems to be a missing texture in 1.15.2.
Latest log: https://gist.github.com/Yourname942/4dd06f3141c138a08e87d78475f055f6

Minecraft 1.15.2
Forge 31.2.36
Abnormals Core 1.0.6
Upgrade Aquatic 1.7.1

**Comment by SmellyModder** [comment]
1.15.2 Upgrade Aquatic will no longer be receiving updates, unfortunately.
