### ISSUE TITLE
Bedrolls being able to be duplicatable by a piston. 

### ISSUE THREAD

**Issue by DavidStain2nd** [minecraftabnormals/Upgrade-Aquatic#191]
For some reason it'll drop it's item when I delete it in creative mode, and by pushing it using a piston.

**Comment by SmellyModder** [comment]
I was looking at the pictures you posted of this in _#upgrade-aquatic_ and it looks like you're using a Quark block? Are you able to reproduce this bug without using that specific block?

**Comment by bageldotjpg** [comment]
Just tested, I think its definitely on our end, because in creative and breaking a bedroll makes it drop itself, so I think fixing that will fix this
