### ISSUE TITLE
1.14.4 Server crash on startup.

### ISSUE THREAD

**Issue by Wissi** [minecraftabnormals/Upgrade-Aquatic#20]
Probably just needs to be updated to latest Forge.

Full crash report [here](https://gist.github.com/Wissi/3de5e010211085737fd0c1e074f3124c).

Using:
Forge-28.1.10
Upgrade Aquatic Wave Three v5 - Beta v1.0.7

We would really like to keep this mod in our new modpack, hope you can fix it soon.

Thanks.

Edit: Actually found that the mod `craftingstation-2.0.3.jar` (Their newest version) will cause your mod to appear on crashlog. Hope that helps - probably just needs to be updated for Forge 1.10+

**Comment by SmellyModder** [comment]
It just needs to be updated to the latest forge yeah. I'll close this issue; we'll try to update ASAP
