### ISSUE TITLE
Ticking world server crash

### ISSUE THREAD

**Issue by CrypticSiri** [minecraftabnormals/Upgrade-Aquatic#200]
Hi, I'm running a 1.15.2-forge-31.2.44 server with Upgrade Aquatic 1.7.1, and it seems that whenever one of the Upgrade Aquatic blocks are loaded, the server crashes. I had not experienced this crash until yesterday, when I first added the mod to my server. The crash only occurs when new chunks are loaded, and if the player that loaded the specific chunk rejoins, the server crashes again.
Crash log / mod list: https://pastebin.com/j5axYQe5
Full server log: https://pastebin.com/htvmCxrJ (pastebin gives this log a warning for some reason, I'm not sure why)

**Comment by SmellyModder** [comment]
Unfortunately, we no longer be support 1.15 versions of the mod.
An incompatibility likely causes that crash; try removing some mods to see if it fixes it.
