### ISSUE TITLE
Terraforged Compat

### ISSUE THREAD

**Issue by TrueDakkon** [minecraftabnormals/Upgrade-Aquatic#205]
It seems like this mod has trouble spawning its entities when playing on a terraforged worlds. I traveled across several oceans and found no mobs other than the nautilus spawning from this mod. I have played on vanilla and BoP worlds and seen them spawning, so I can confirm to that extent that it is the terraforged worlds that seem to be causing some kind of compatability issue here.

**Comment by SmellyModder** [comment]
I'm not sure what the cause for this could be without further knowledge of what Terraforged is doing to generation and/or manipulating entity spawns. You should open up an issue on their side to see what might be causing it and then re-open this issue if you find a cause.
