### ISSUE TITLE
Crash while ticking entity

### ISSUE THREAD

**Issue by LlubNek** [minecraftabnormals/Upgrade-Aquatic#23]
Using FTB Unstable 1.14 version 1.10.0 plus the following mods
Mouse Tweaks
Ore Excavation
SwingThroughGrass
Clumps
BetterAdvancements
Hwyla
KleeSlabs
Fast Leaf Decay
DRP - Global Data Pack
Ring of Repair [FORGE]
Ring of the Miner [FORGE]
Ring of the Enderchest [FORGE]
Ring of Blink [FORGE]
VoxelMap

... minus
Mappy
Assisted Progression

[crash-2019-10-13_02.50.02-server.txt](https://github.com/minecraftabnormals/Upgrade-Aquatic/files/3721503/crash-2019-10-13_02.50.02-server.txt)
[latest.zip](https://github.com/minecraftabnormals/Upgrade-Aquatic/files/3721504/latest.zip)

**Comment by SmellyModder** [comment]
Thanks I'll look into it. Appears there's a small chance the new drowned drops crash the game

**Comment by SmellyModder** [comment]
Drowned dropping corals got removed recently so I'll close this
