### ISSUE TITLE
Mulberry Vines Cross Mod Compat

### ISSUE THREAD

**Issue by HyDefier** [minecraftabnormals/Upgrade-Aquatic#322]
I've been playing Upgrade aquatic in a modpack that awards skill experience for farming; however, various modded crops including mulberry vines are not awarding farming xp, despite behaving like a crop. This is because they are not tagged as being a crop. Please add the "minecraft:crops" tag to increase cross-mod compatibility.

**Comment by HyDefier** [comment]
Correction: having talked with the developer of the specific farming mod they said for crops to be supported they need to inherit CropBlock and set the age property there and set getAgeProperty, rather than creating a new arbitrary age value.

**Comment by HyDefier** [comment]
I guess adding the minecraft:crops will only let bees interact with them.. as far as I know

**Comment by bageldotjpg** [comment]
Due to how the block is designed, it intentionally does not inherit CropBlock - perhaps theres another option you can do with the mod?
