### ISSUE TITLE
River Trees cover up islands

### ISSUE THREAD

**Issue by Shepelo2** [minecraftabnormals/Upgrade-Aquatic#327]
I was looking around my world, and saw an island that had A LOT of river trees. Perhaps the spawn frequency of the trees can be tweaked a bit to fix this.
![2022-09-01_12 47 03](https://user-images.githubusercontent.com/90096546/187979814-db95752d-344f-492b-9baa-012b575acccd.png)

**Comment by bageldotjpg** [comment]
Is this vanilla biome generation?
