### ISSUE TITLE
[1.16.5] Glow Squid rendering error with shaders.

### ISSUE THREAD

**Issue by AlienXtream** [minecraftabnormals/Upgrade-Aquatic#333]
minor issue with the glow squid and shaders using the "Oculus" shader mod (forge prot of iris) and complementary shaders. dont know if its shader pack specific.

![image](https://user-images.githubusercontent.com/12606809/194785873-14cacd7a-c594-4223-8f32-79c8c18194db.png)

to be clear, they aren't doing the old "flying squid" glitch. they are actually attached to the screen and move with the camera. i understand if 1.16.5 isn't supported anymore (and with glow squids being a vanilla thing in later versions its "not your problem"). just thought i'd mention it at least. worst case other users searching this issue will find this and be informed. best case some minor update can be pushed. either way i've mentioned it here for convenience and documentation :)

**Comment by bageldotjpg** [comment]
Unfortunately 1.16.5 & shader issues are not supported, sorry, usually we can't fix those

**Comment by AlienXtream** [comment]
thats fair enough. technically it would have been on the shaders side anyway. it (obviously) works as intended in the versions where they are vanilla mobs.
