### ISSUE TITLE
Biome Mods Not Loading?

### ISSUE THREAD

**Issue by IAmOrion15** [minecraftabnormals/Upgrade-Aquatic#335]
I am not sure if this is just because 1.18 Upgrade Aquatic is still in beta... But Biomes Oh Plenty and Oh The Biomes You'll Go do not load any biomes when I am using Upgrade Aquatic. But the nether and end biomes are still loading. Not only that, the overworld underground stones are loading and the beach palm trees are loading. The biomes can be loaded with the /locatebiome... but you can't actually find them (they don't exist).

**Comment by SmellyModder** [comment]
Use the latest version of Blueprint for 1.18.2.
