### ISSUE TITLE
Wiki Missing Coral Info & Guidebook

### ISSUE THREAD

**Issue by yancypro** [minecraftabnormals/Upgrade-Aquatic#336]
All,
I can't find information about Coral. How to mine it, What it can be used for, etc.. Also, was only able to find the Wiki here in the Github website. Would be very helpful if it were accessible on its CurseForge mod site as well and/or a guidebook as part of the mod, to help with this info In-Game.  
Please send me a message at yancypro@gmail.com, to help with this. 
Thanks.

**Comment by bageldotjpg** [comment]
Wiki is missing a lot. It's a heavy work in process & commitment.
