### ISSUE TITLE
Issue with Squid/Glow Squid Ink applying Status Effects

### ISSUE THREAD

**Issue by LaGz4643** [minecraftabnormals/Upgrade-Aquatic#338]
Squids/Glow Squids will only apply Blindness/Glowing to an entity if part of the entity's bounding box is South, East, and above the Squid's bounding box.

To reproduce this issue, spawn a squid on flat ground and stand northwest (negative x and z) from the squid. Attacking it will not give you blindness no matter how close you are to it (unless you get close enough to touch the squid's bounding box).
Now, stand southeast (positive x and z) from the squid and attack it. You can stand up to about 2 blocks away and still receive the Blindness effect.

Also, spawning a squid on a 2 block tall tower of blocks, standing below, and attacking it will never give you Blindness no matter which side you attack it from.

Note: The direction that the squid is facing has no affect on how it applies Status Effects.

**Comment by SmellyModder** [comment]
Confirmed. It appears to be a mismapping that happened during the port.
