### ISSUE TITLE
glass and other transparent blocks (grass etc...) obstructing the elder eye view

### ISSUE THREAD

**Issue by ClephLeSDF** [minecraftabnormals/Upgrade-Aquatic#348]
![2023-02-05_14 12 49](https://user-images.githubusercontent.com/16508989/216821786-a21824b9-68cc-4c74-afc9-11b3a14b91a2.png)
![2023-02-05_14 12 52](https://user-images.githubusercontent.com/16508989/216821789-51bbe2cc-9d1a-4c95-9139-58cb2e11469b.png)

**Comment by bageldotjpg** [comment]
Fixed in 1.20.1
