### ISSUE TITLE
[1.18.2] Thrasher Server Crash

### ISSUE THREAD

**Issue by Brown-bricks** [minecraftabnormals/Upgrade-Aquatic#349]
Server-side ticking entity crash seemingly related to the thrasher AI
[crash-2023-02-11_20.27.49-server.txt](https://github.com/team-abnormals/upgrade-aquatic/files/10715232/crash-2023-02-11_20.27.49-server.txt)

**Comment by Reshy** [comment]
Think I've encountered the same issue:  https://pastebin.com/9VaYwhQm

**Comment by DTX3** [comment]
Yep same. Also, logs spammed with [Server thread/WARN] [minecraft/ServerLevel]: Tried to add entity upgrade_aquatic:thrasher but it was marked as removed already allot of the time.

**Comment by CatoConroy** [comment]
Same problem here. Do we know if this is isolated to 1.18.2?

**Comment by annastropha** [comment]
It's not - I see it on 1.19.3 with [Apathy Mod](https://www.curseforge.com/minecraft/mc-mods/apathy-mod)

[Crashlog](https://pastebin.com/JC8Ayymk)

**Comment by bhodges7** [comment]
Same issue on 1.19.2 https://pastebin.com/7tBraLWz

**Comment by LaGz4643** [comment]
Steps to reproduce this issue:
1. Summon a Thrasher in an enclosed area of water
2. Summon any type of fish in the water
3. Right after the Thrasher grabs the fish in its mouth, run a command to kill the fish
(`/kill @e[type=salmon,limit=1,sort=nearest]`, replace `salmon` with the id of the fish you summoned)
4. The game should crash after a few seconds if the fish dies and finishes its death animation before the Thrasher finishes its attack animation.

There's a chance the game will not crash if the fish dies at the wrong time, so you might have to repeat these steps again to reproduce this issue.
