### ISSUE TITLE
 [1.18.2] Glow Squid Render Server Crash

### ISSUE THREAD

**Issue by FoxyFox909** [minecraftabnormals/Upgrade-Aquatic#350]
[crash-2023-02-28_12.57.10-client.txt](https://github.com/team-abnormals/upgrade-aquatic/files/10853693/crash-2023-02-28_12.57.10-client.txt)

**Comment by FoxyFox909** [comment]
The setting used to disable UA Glow Squid renderer is not working. I am still crashing from UAGlowSquidRenderer

**Comment by MagotrapTheArchmage** [comment]
[crash-2023-12-04_20.53.53-client.txt](https://github.com/team-abnormals/upgrade-aquatic/files/13550466/crash-2023-12-04_20.53.53-client.txt)
I have a similar issue

**Comment by FoxyFox909** [comment]
This mod seems abandoned on 1.18.2. I've removed it from my pack until something about that changes.
