### ISSUE TITLE
[1.19.2] Missing #bedrolls block tag for easier customization

### ISSUE THREAD

**Issue by thelegitdolt** [minecraftabnormals/Upgrade-Aquatic#351]
Though bedroll items are correctly tagged as #upgrade_aquatic:bedrolls, there is no block tag holding a list of bedrolls.

**Comment by thelegitdolt** [comment]
Note that vanilla is known to have block tag for colored blocks-- as the #minecraft:carpets block tag exists.

**Comment by bageldotjpg** [comment]
Vanilla doesn't have tags for a lot of colored blocks, tags are added when they are used - a bedrolls block tag doesn't really need to exist because it isn't used, unlike the item tag. If a datapack needs a bedrolls block tag, it can add it
