### ISSUE TITLE
Command to spawn specific pike variants?

### ISSUE THREAD

**Issue by MinecraftPerson** [minecraftabnormals/Upgrade-Aquatic#352]
I'm working on an aquarium and need all the pike variants for my freshwater section, could someone hepl?

**Comment by SmellyModder** [comment]
Use the integer tag `"PikeType"` in the entity's NBT.
All IDs are listed here: https://github.com/team-abnormals/upgrade-aquatic/blob/1.19.x/src/main/java/com/teamabnormals/upgrade_aquatic/common/entity/animal/PikeType.java
