### ISSUE TITLE
Pike has no texture

### ISSUE THREAD

**Issue by MrJorman** [minecraftabnormals/Upgrade-Aquatic#355]
Pike has no texture 
![image](https://user-images.githubusercontent.com/55187962/225887333-24b92fe1-6c79-4e20-b948-4c0135d63be5.png)

**Comment by thelegitdolt** [comment]
this is literally me when pikes has no texture

**Comment by thelegitdolt** [comment]
In 1.19.2 latest release and every pike variant seem to correctly have a texture. Perhaps an optifine glitch?

**Comment by SmellyModder** [comment]
There has to be something else besides UA causing this issue. Pikes texture their models like vanilla does, and the pike's texture depends on its type (all of which are hardcoded).
