### ISSUE TITLE
Bedroll sides don't render

### ISSUE THREAD

**Issue by WenXin20** [minecraftabnormals/Upgrade-Aquatic#36]
Minecraft v1.14.4
Forge v28.1.90
Upgrade Aquatic v6-108

If a bedroll is placed down with a block behind it, the sides of the bedroll don't render.

**Comment by SmellyModder** [comment]
I can't seem to reproduce the issue you're experiencing. Are you using any shaders and can you provide a visual display of the bug?

**Comment by WenXin20** [comment]
No shaders, but I'll provide an image soon.

**Comment by WenXin20** [comment]
![2019-11-21_16 15 33](https://user-images.githubusercontent.com/12000593/69381528-9135ff80-0c7a-11ea-91c2-166a43f1c7ae.png)

**Comment by SmellyModder** [comment]
Thanks, will fix soon

**Comment by SmellyModder** [comment]
This has been fixed in-dev(look at latest commit). I will close this issue now, and it will be fixed in the next build, which will be releasing hopefully soon. Thanks for reporting :)
