### ISSUE TITLE
Config Disable Bedroll 1.19.2

### ISSUE THREAD

**Issue by zachsai** [minecraftabnormals/Upgrade-Aquatic#368]
Hi,
Could you add a config to disable bedrolls from villager trades / entirely?

I use the mod Sleep Tight and this mod's bedrolls break the immersion.

I disabled the recipes of bedrolls, but if villagers can trade them, it breaks the whole thing

**Comment by bageldotjpg** [comment]
There is indeed a config to disable bedroll trades in the config
