### ISSUE TITLE
Separate Creative tab for items

### ISSUE THREAD

**Issue by T3sT3ro** [minecraftabnormals/Upgrade-Aquatic#372]
Hi, it would be nice to have a separate creative tab for all the things added by this mod.

**Comment by bageldotjpg** [comment]
No plans for this at the moment

**Comment by T3sT3ro** [comment]
Why though? It's pretty simple to do that and makes it less messy, no? Also, that's none of my business, but shouldn't you keep the issue open then?

**Comment by bageldotjpg** [comment]
We intentionally put our content alongside vanilla stuff, to feel more like part of the game.
The issue is closed because its not a feature we want, therefore not an issue.
