### ISSUE TITLE
[1.19.2] Chests not showing up in JEI

### ISSUE THREAD

**Issue by vizthex123** [minecraftabnormals/Upgrade-Aquatic#380]
Very odd bug that I've never seen before, but both the Driftwood and River chests don't show up in JEI even though their recipes do.

Driftwod:
![image](https://github.com/team-abnormals/upgrade-aquatic/assets/31721920/65567cff-1e3c-4be1-8c76-fa7e129b041c)

![image](https://github.com/team-abnormals/upgrade-aquatic/assets/31721920/6617bf77-7469-44cb-84d2-9732951a460d)

River:
![image](https://github.com/team-abnormals/upgrade-aquatic/assets/31721920/b021c358-f473-46bb-957b-d7bcbaf2cdcd)

![image](https://github.com/team-abnormals/upgrade-aquatic/assets/31721920/b0d4032a-88e7-48dd-80aa-86c868bd0e7e)

Log:
[latest.log](https://github.com/team-abnormals/upgrade-aquatic/files/12823383/latest.log)

**Comment by bageldotjpg** [comment]
Yeah weird side effect, our wood variant stuff takes priority for Woodworks, and only appear in creative tabs when that is present due to some limitations, but they can still be crafted is Quark or present.
