### ISSUE TITLE
log error without your mod installed?

### ISSUE THREAD

**Issue by Aceplante** [minecraftabnormals/Upgrade-Aquatic#384]
Error loading class: com/teamabnormals/upgrade_aquatic/common/block/FloweringRushBlock (java.lang.ClassNotFoundException: com.teamabnormals.upgrade_aquatic.common.block.FloweringRushBlock)

**Comment by bageldotjpg** [comment]
This means you have another mod installed attempting to access that class, perhaps a dependency or compatibility mod. Uninstall that mod or install this mod to fix it.

**Comment by RN0000** [comment]
> Error loading class: com/teamabnormals/upgrade_aquatic/common/block/FloweringRushBlock (java.lang.ClassNotFoundException: com.teamabnormals.upgrade_aquatic.common.block.FloweringRushBlock)

Do you remember what mods you were using? I'm having the same issue...
