### ISSUE TITLE
Upgrade Aquatic 1.20.1 won't load because it lists a version of blueprint that isnt a thing

### ISSUE THREAD

**Issue by fabton** [minecraftabnormals/Upgrade-Aquatic#395]
as stated above the mod requires blueprint but it want blueprint version 7.1.0 but blueprint only has a max version of 7.0.3

**Comment by bageldotjpg** [comment]
https://modrinth.com/mod/blueprint/version/7.1.0

Curseforge has not accepted the file yet.
