### ISSUE TITLE
[Forge 1.20.1] Drift and Riverwood items don't have recipes 

### ISSUE THREAD

**Issue by vizthex123** [minecraftabnormals/Upgrade-Aquatic#403]
Looks like the Boards, both Bookshelves, Chests, Boat with Furnace, Beehives, Ladders, and Large Boat are affected.

**Comment by bageldotjpg** [comment]
These are compatibility items for [Woodworks](https://modrinth.com/mod/woodworks) and [Boatload](https://modrinth.com/mod/boatload) respectively.
