### ISSUE TITLE
Turtle shell durrability drain is disproportianal to air drain

### ISSUE THREAD

**Issue by Ganpan14O** [minecraftabnormals/Upgrade-Aquatic#405]
As the title states it seems the durability loss of the turtle shell has nothing to air drain speed, even while in a bubble column or the aoe of a conduit durability drains, and from this I'd presume that respiration is ineffective too.

**Comment by bageldotjpg** [comment]
Not sure what your point is, the rework makes turtle shells give water breathing, and durability drain is completely unrelated to the air drain speed, because air wouldn't be draining.

**Comment by Ganpan14O** [comment]
> Not sure what your point is, the rework makes turtle shells give water breathing, and durability drain is completely unrelated to the air drain speed, because air wouldn't be draining.

The issue is that effects such as conduit power and respiration are completely pointless with a turtle shell under this rework as the durability still drains and just as fast. If this is as intended I understand, I just made this as it felt like an unintentional debuff to turtle shells.

**Comment by bageldotjpg** [comment]
Well yes they don't stack because inherently they work differently but overall the turtle shell is more useful
There will be an option to disable the change in the next update

**Comment by Ganpan14O** [comment]
There is already an option to disable it, it just seems odd that it's fully incompatible with 2 vanilla features that normally synergize well with turtle shells.

Edit: The option is in the config but currently non functional
