### ISSUE TITLE
Thrasher's thrashing works in Creative

### ISSUE THREAD

**Issue by Bratistolf** [minecraftabnormals/Upgrade-Aquatic#41]
![2019-12-03_11 35 17](https://user-images.githubusercontent.com/39115889/70026471-b6533800-15c1-11ea-9bd0-f4b24c01799c.png)
![2019-12-03_11 35 31](https://user-images.githubusercontent.com/39115889/70026472-b6533800-15c1-11ea-9e7a-af08795f4182.png)
![2019-12-03_11 35 37](https://user-images.githubusercontent.com/39115889/70026473-b6533800-15c1-11ea-93fd-22e48ad5d0c0.png)

Minecraft v1.14.4
Forge v28.1.90
Upgrade Aquatic 1.0.9 v32

If you attack the thrasher while next to it in creative mode, it'll seize you, even thought it shouldn't do that.

**Comment by SmellyModder** [comment]
Fixed in Dev
