### ISSUE TITLE
1.20.1 pike do not spawn

### ISSUE THREAD

**Issue by Poopchungus** [minecraftabnormals/Upgrade-Aquatic#413]
pike barely spawn like they did in the previous update of the game and they do not spawn at all when you add mods like terralith or biomes o plenty to the mix

**Comment by AtiusAmy** [comment]
Seems to be my experience too, I've been exploring for a while and I can't seem to find any Upgrade Aquatic mobs

NVM: I see Lionfish now, still no pike tho

**Comment by Poopchungus** [comment]
is anyone going to take a look at this

**Comment by bageldotjpg** [comment]
They do spawn, they just now have a reliance on Pickerelweed so pickerelweed must be present for them to spawn

**Comment by Poopchungus** [comment]
oh :(
