### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by m0thknight** [minecraftabnormals/Upgrade-Aquatic#418]
[crash-2024-07-18_22.15.13-server.txt](https://github.com/user-attachments/files/16302435/crash-2024-07-18_22.15.13-server.txt)

**Comment by kitovoi111** [comment]
[crash-2024-08-08_14.59.52-server.txt](https://github.com/user-attachments/files/16548738/crash-2024-08-08_14.59.52-server.txt)
crash too problem. fix please.

**Comment by kitovoi111** [comment]
1.19.2 fix??
