### ISSUE TITLE
Concurrent Modification Exception with reliquary and thrasher mob

### ISSUE THREAD

**Issue by superdude808** [minecraftabnormals/Upgrade-Aquatic#419]
Minecraft version: 1.20.1
upgrade aquatic version: 6.0.0.
forge version: 47.3.5.
blueprint version: 7.1.0.

So every time I get picked up and attacked by the thrasher the game crashes **every single time** no exceptions.

Now to cut a line of inquiry off I do not have a reliquary charm equipped nor do I have one in my inventory.

now from what the crash log says I think it is an interaction between reliquary's mob charm system that screws with how mobs can see and track the player and the thrasher's unique way of targeting thing to attack them but that's all I know since I don't code enough to figure out more than that.

[crash-2024-08-08_14.35.44-client.txt](https://github.com/user-attachments/files/16538943/crash-2024-08-08_14.35.44-client.txt)

**Comment by bageldotjpg** [comment]
Looks to be a Reliquary issue
