### ISSUE TITLE
Game Crashes On Version 1.16.5

### ISSUE THREAD

**Issue by BerkinOzcan88** [minecraftabnormals/Upgrade-Aquatic#432]
I am trying to play Crucial 2 modpack on 1.16.5 but the game crashes randomly while playing. It seems like a files name got changed to "refin.png" with a normal "i" to "redfın.png" with an "ı" because my game is Turkish. 

The crash report:
[crash.txt](https://github.com/user-attachments/files/18268877/crash.txt)

**Comment by bageldotjpg** [comment]
1.16.5 is no longer supported but this can likely be fixed via renaming the file
