### ISSUE TITLE
Please add a status effect to insomnia

### ISSUE THREAD

**Issue by trevorjd** [minecraftabnormals/Upgrade-Aquatic#47]
Having a darkened border around my game isn't pleasant and with no indication whatsoever as to what's causing it, it's rather frustrating. Your mod is one of almost 150 in FTB Unstable so it's simply not practical to closely examine every mod's info page and even then, most mods aren't particularly well documented.

Please add a status effect that indicates when the player is being affected by insomnia. Even if it doesn't indicate which mod is giving it, it will at least give people an idea that sleeping will fix the problem.

**Comment by SmellyModder** [comment]
You can just turn the insomnia overlay off in the config.

**Comment by SmellyModder** [comment]
It's been turned off by default since the first release build.

**Comment by trevorjd** [comment]
> You can just turn the insomnia overlay off in the config.

You can only do that if you know which mod is adding the overlay! The problem is not the overlay per se, it's not knowing which of ~150 mods in a professionally-compiled pack adds it.

> It's been turned off by default since the first release build

Like most players, I simply installed a professionally-compiled modpack. Presumably they've turned it on.

**Comment by SmellyModder** [comment]
I'll discuss this with others

**Comment by SmellyModder** [comment]
I do understand what you're saying though. Seems... annoying
