### ISSUE TITLE
Driftwood button's hit box is wrong and it is annoying

### ISSUE THREAD

**Issue by ilja615** [minecraftabnormals/Upgrade-Aquatic#66]
You can stand on driftwood button, and it is inconsistend with other buttons.

(for example try putting a sideways button on a wall, you can stand on it.. )

The hit box has to be changed i think

**Comment by SmellyModder** [comment]
You sure other wooden buttons don't do this?

**Comment by SmellyModder** [comment]
And if you want it fixed ASAP make a pr to do it

**Comment by five0five** [comment]
fixed in 1.4.5, opposite now applies to the trapdoor now however that will soon be fixed
