### ISSUE TITLE
Upgrade Aquatic disables some JER catagories

### ISSUE THREAD

**Issue by IronPiston** [minecraftabnormals/Upgrade-Aquatic#67]
[JER Version](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer): 1.14.4-0.10.0.70
Upgrade-Aquatic Version: 1.4.5

JER adds adds tabs to JEI, but having Upgrade Aquatic installed disables some of them:
- Plant drops
- World Gen
- Mob drops
- Dungeon Chests  

Does this happen because Upgrade Aquatic adds mobs, loot, and other world gen?

**Comment by SmellyModder** [comment]
JER is a client-side mod, it really shouldn't be affected by this mod. Go report this to the JER devs and see if they know what the cause is because I don't know how the code in JER works.
