### ISSUE TITLE
Pike super spawning

### ISSUE THREAD

**Issue by TheDarkPreacher** [minecraftabnormals/Upgrade-Aquatic#7]
Not sure if this is intended behavior, or a bug, but pike appear in very large numbers in version Alpha v1.0.3

Screenshot attached. (taken from a distance to try and avoid possible crash repeat)
![2019-07-30_04 43 27](https://user-images.githubusercontent.com/15058826/62119399-15581780-b285-11e9-8d16-62688f97f7ad.png)

**Comment by five0five** [comment]
> Reporting this to McJty as well for The One Probe:
> Was exploring a singleplayer instance of the latest Devcraft pack (The one EpicSquid just released) and came across a swamp where a ton of pike had spawned. Looked at said pike, framerate dropped, then got a crash. Crashlog pastebin: https://pastebin.com/JcUKyuiU
> Not sure if it was an issue with too many pike in one area, an issue rendering the pike in the TOP preview, or a pike rendering in incorrectly, since I'm rubbish at reading a crash log.
> Version: Alpha v1.0.,3
> TOP Version: 1.14.-1.4.31-alpha

**Comment by SmellyModder** [comment]
The crash is actually caused by server world casting to client world for the item in its mouth spawning. I've just fixed it and I'm working on fixing the spawning right now; a hotfix will be out soon

**Comment by SmellyModder** [comment]
This issue has now been fixed
