### ISSUE TITLE
[1.14.4] Got this in the logs, anything to worry about?

### ISSUE THREAD

**Issue by Gbergz** [minecraftabnormals/Upgrade-Aquatic#73]
Message in logs: [https://gist.github.com/Gbergz/0df3acd4b0014753c56c779b66c203da](https://gist.github.com/Gbergz/0df3acd4b0014753c56c779b66c203da)

As the title says, is this anything to worry about? Reporting this for visibility and if its something that should be fixed.

Forge: **28.1.107**
MC: **1.14.4**
Mod-Version: **1.4.7**

**Comment by SmellyModder** [comment]
This is a bug with JRE, report it to them
