### ISSUE TITLE
Beachgrass Thatch Renders Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [minecraftabnormals/Upgrade-Aquatic#75]
`Minecraft v1.14.4`
`Forge v28.1.109`
`Upgrade Aquatic v1.4.7`

Beachgrass Thatch will render with render flowing down its sides if placed underwater.

![2020-01-11_23 40 01](https://user-images.githubusercontent.com/12000593/72214685-b271da00-34cc-11ea-8d35-ad04026ae85e.png)

**Comment by SmellyModder** [comment]
There's no real way to fix this entirely, unfortunately. I will close this issue

**Comment by WenXin20** [comment]
Would allowing it to be waterlogged fix it?
