### ISSUE TITLE
[1.14.4, v1.4.10] World load stuck @ 100% on player.join

### ISSUE THREAD

**Issue by dreckz** [minecraftabnormals/Upgrade-Aquatic#88]
Expected:
**Supposed to create a world and load into it normally.**

Actual:
**World creation event gets stuck at 100% and doesn't spawn the player in.**

Once I removed the mod from the pack, I was able to create a world and load into it properly.

Crash log:
[crash-2020-02-13_01.54.07-server.txt](https://github.com/minecraftabnormals/Upgrade-Aquatic/files/4197114/crash-2020-02-13_01.54.07-server.txt)

**Comment by SmellyModder** [comment]
You've got quite a lot of mods there. Try running the mod alone and see if the issue persists.

**Comment by freevortex** [comment]
I just wanted to let you know that it seems to be some sort of conflict between Upgrade Aquatic and The Endergetic Expansion. I had the same issue, removed Endergetic, and am now loading normally.
