### ISSUE TITLE
Will this mod be realised for 1.12.2

### ISSUE THREAD

**Issue by Azuralie** [minecraftabnormals/Upgrade-Aquatic#93]
Hello ! I love this mod but unfortunatly, I'm playing on 1.12.2 with my friends… I would love to know if you could release this mod for 1.12.2 !

**Comment by fivelol** [comment]
this mod upgrades 1.13, so having it on 1.12 would be a bit pointless. it's better for you to (respectfully) ask other mods that are still on 1.12.2 to update, rather than ask other mods to downgrade, so that everybody can enjoy the content on newer versions.
