### ISSUE TITLE
[1.15.2] Upgrade Aquatic crashes on new world.

### ISSUE THREAD

**Issue by dreckz** [minecraftabnormals/Upgrade-Aquatic#94]
UA: 1.5.0
Minecraft: 1.15.2
Forge: 31.1.35

Upon creating a new world to play in, the game freezes and doesn't load properly and crashes.

Crash Log:
[crash-2020-04-03_15.41.21-server.txt](https://github.com/minecraftabnormals/Upgrade-Aquatic/files/4429889/crash-2020-04-03_15.41.21-server.txt)

**Comment by SmellyModder** [comment]
Do you have any other mods installed that mess with sleeping?
