### ISSUE TITLE
[1.15.2] Prismarine Coral Blocks with Coral or Coral Fans do not respect Charm's Magnetic enchantment.

### ISSUE THREAD

**Issue by ridjack** [minecraftabnormals/Upgrade-Aquatic#97]
Charm's Magnetic enchantment causes mined blocks to go directly to your inventory. When mining a Prismarine Coral Block that has a Prismarine Coral or Coral Fan on it, the block drops as if there were no Magnetic enchantment on the tool. This problem does not occur with Elder Prismarine Coral Blocks; they are magnetized normally. 

I previously noticed this problem in the 1.14.4 version as well, but at the time I wasn't certain what the conditions were. 

svenhjol/Charm#235

**Comment by SmellyModder** [comment]
This is an issue on their side from what I can tell, closing this. Thanks for the report.
